--- ## master playbook for webserver
- hosts: centos
  user: ansible
  sudo: yes
  connection: ssh
  pre_tasks:
  - name: role start
    raw: date > /home/ansible/startrole.log
  roles:
    - debian_webserver
  post_tasks:
  - name: role end
    raw: date > /home/ansible/endrole.log
